name: Compare Providers

on:
  workflow_dispatch:
  # push:
  
env:  # Define global environment variables for all jobs
    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    CLOUDFLARE_AI_TOKEN: ${{ secrets.CLOUDFLARE_AI_TOKEN }}
    GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    HYPERBOLIC_API: ${{ secrets.HYPERBOLIC_API }}
    OPEN_AI_API: ${{ secrets.OPEN_AI_API }}
    PERPLEXITY_AI_API: ${{ secrets.PERPLEXITY_AI_API }}
    TOGETHER_AI_API: ${{ secrets.TOGETHER_AI_API }}
    ANTHROPIC_API: ${{ secrets.ANTHROPIC_API }}
    AZURE_LLAMA_70B_API: ${{ secrets.AZURE_LLAMA_70B_API }}
    AZURE_LLAMA_8B_API: ${{ secrets.AZURE_LLAMA_8B_API }}
    AWS_BEDROCK_ACCESS_KEY_ID: ${{ secrets.AWS_BEDROCK_ACCESS_KEY_ID }}
    AWS_BEDROCK_SECRET_ACCESS_KEY: ${{ secrets.AWS_BEDROCK_SECRET_ACCESS_KEY }}
    AWS_BEDROCK_REGION: ${{ secrets.AWS_BEDROCK_REGION }}
    folder: benchmarking/experiments/providers_streaming/single_model  # common folder for experiment configs
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Experiment
      run: python main.py -c benchmarking/experiments/compare_providers_test.json

    - name: Upload Experiment Outputs
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: test-experiment-results
        path: benchmark_graph

  anthropic:
    runs-on: ubuntu-latest  
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Experiment
        run: python main.py -c ${{ env.folder }}/anthropic.json # how to put folder here?

      - name: Upload Experiment Outputs
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: anthropic-experiment-results
          path: benchmark_graph

  cloudflare:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Experiment
        run: python main.py -c ${{ env.folder }}/cloudflare.json

      - name: Upload Experiment Outputs
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: cloudflare-experiment-results
          path: benchmark_graph
          
  perplexityai:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Experiment
        run: python main.py -c ${{ env.folder }}/perplexity_ai.json

      - name: Upload Experiment Outputs
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: perplexityai-experiment-results
          path: benchmark_graph

  aws:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Experiment
        run: python main.py -c ${{ env.folder }}/aws.json

      - name: Upload Experiment Outputs
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: aws-experiment-results
          path: benchmark_graph

  azure:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Experiment
        run: python main.py -c ${{ env.folder }}/azure.json

      - name: Upload Experiment Outputs
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: azure-experiment-results
          path: benchmark_graph
          
  togetherai:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Experiment
        run: python main.py -c ${{ env.folder }}/together_ai.json

      - name: Upload Experiment Outputs
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: togetherai-experiment-results
          path: benchmark_graph

  # OpenAI
  openai:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Experiment
        run: python main.py -c ${{ env.folder }}/open_ai.json

      - name: Upload Experiment Outputs
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: openai-experiment-results
          path: benchmark_graph

  # Hyperbolic
  hyperbolic:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Experiment
        run: python main.py -c ${{ env.folder }}/hyperbolic.json

      - name: Upload Experiment Outputs
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: hyperbolic-experiment-results
          path: benchmark_graph

  # Google Gemini
  google_gemini:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Experiment
        run: python main.py -c ${{ env.folder }}/google.json

      - name: Upload Experiment Outputs
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: google-gemini-experiment-results
          path: benchmark_graph

  # Groq
  groq:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Experiment
        run: python main.py -c ${{ env.folder }}/groq.json

      - name: Upload Experiment Outputs
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: groq-experiment-results
          path: benchmark_graph
