name: Python Tests

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
  # push:
  #   branches:
  #     - main  # Run on push to the main branch
  # pull_request:
  #   branches:
  #     - main  # Run on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest available Ubuntu runner

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Step 4: Run pytest with coverage
      - name: Run tests with coverage
        env:
          AWS_ACCESS_KEY_ID: mock_access_key_id
          AWS_SECRET_ACCESS_KEY: mock_secret_access_key
          AWS_REGION: us-east-1
        run: |
          pytest --cov --cov-config=.coveragerc --cov-report=xml --cov-report=term-missing

     # Step 5: Run pylint
      - name: Run pylint
        run: |
          pylint --fail-under=8 --ignore=test_files ./
        continue-on-error: false  # Fail if score is below 8

      # Step 6: Run flake8
      - name: Run flake8
        run: |
          flake8 ./  # Run flake8 on specified directories
