name: Python Tests

# Controls when the workflow will run
on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest available Ubuntu runner

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run pytest with coverage
      - name: Run tests with coverage
        run: |
          pytest --cov=providers --cov=main --cov-report=xml --cov-report=term-missing

     # Step 5: Run pylint
      - name: Run pylint
        run: |
          pylint --fail-under=8 --ignore=test_files ./
        continue-on-error: false  # Fail if score is below 8

      # Step 6: Run flake8
      - name: Run flake8
        run: |
          flake8 ./  # Run flake8 on specified directories

      # Step 7: Run codespell
      - name: Run codespell
        run: |
          codespell ./ # Run codespell on specified directories

